### PR TITLE
Adding Kaliya's contribution to pre-read.

### PR DESCRIPTION
**Pull request by Identitywoman**

### CODE REVIEW

**Comment by ChristopherA** [comment]
Can you put a short file in the repo, with your link in it, as many people just download the files.

**Comment by Identitywoman** [comment]
I just went to the front page to see the link to my paper there... and it wasn't there.  
Then I find this.. you aren't sharing the link? Thanks Chris. Sharing the link to the blog where I literally spent 5 hours doing the collecting and formatting would be respectful. 
I'll see what I can do in terms of turning it into a downloadable form. If people really wanna download something they can go to my blog and "print it" 
I will see about formatting it into a paper it will take days but it is 8000 words long... so 24 pages. You know you could fund Shannon to do it... if you really want it in that format.

**Comment by ChristopherA** [comment]
I’m not asking for the full blog post, but a short text file with an abstract & link.

**Comment by Identitywoman** [comment]
Look at these .md files that are linked to. https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/blob/master/topics-and-advance-readings/DID-Auth%20protocol.md
They aren't PDFs for download. One has to go and make them PDFs to "download" they aren't just pdfs. 
There is nothing wrong with linking to the ACTUAL post on my blog given the nature of the discussion that happened and the 5 hours of formatting. Not having it "live" and available for the last 7 days is disrespectful. 
Thank you for clarifying what you wanted. I am off to the NewCo Shift Forum right now. I will be hosting a lunch discussion tomorrow on Self-Sovereign Identity and doing a report out the following day. I will see about getting you what you asked for in the mean time put up a link to my blog post with this critical industry conversation that I lead on Twitter.

**Comment by shannona** [comment]
Apologies for not directly contacting you on this late last week, @Identitywoman ; Christopher had asked me to, but I got waylaid by a health crisis and an operational crisis. 

If you can just send me (or PR) a short file that has:

==
# Title

[a paragraph or so of abstract]

[link to your blog]
==

That will do the trick.

Thanks!

**Comment by shannona** [comment]
Just let me know when we have a short stub that we can add to the archive, @Identitywoman ; a bew PR will be fine, or you can mail it to me at shannona@skotos.net, if you prefer.

**Pull request closed without merging**
